### ISSUE TITLE
Attempted to call an undefined method named "getCurrencyPrecision" of class "Shopware\Core\Framework\Context".

### ISSUE THREAD

**Issue by JonathanDeBelg** [myparcelnl/shopware6-deprecated#9]
Hi,

I am getting the following error when adding a product to my cart, with a myparcel shipping option selected as default shipping; 
`Attempted to call an undefined method named "getCurrencyPrecision" of class "Shopware\Core\Framework\Context".`

How can i fix this issue?

**Comment by RichardPerdaan** [comment]
Dear @JonathanDeBelg,
Are you still experiencing this issue with the latest version of the MyParcel plugin?

**Comment by RichardPerdaan** [comment]
Hi @JonathanDeBelg  ,

I have tried to reproduce this problem several times. But unfortunately I don't see the problem.

Since there has no response since May 9, I am closing the issue.

If this problem is still present, you can always open the issue again.
